name: Push to master

on:
  push:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: .go_version
      - name: Unit tests
        run: make test
      - name: Code coverage
        uses: codecov/codecov-action@v4
        with:
          files: build/coverage.txt
          # After codecov/codecov-action@v4, tokenless uploading of coverage files to non-public repo is unsupported.
          # To enable codecov analysis in your forked repo. Please configure CODECOV_TOKEN in your repository secrets.
          # Ref: https://docs.codecov.com/docs/adding-the-codecov-token
          token: ${{ secrets.CODECOV_TOKEN }}
